window.ITData={version:"1.1",projects:[
{id:1,code:"IRT-۱۴۰۳-۰۰۱",name:"دامداری نمونه",domain:"دامپروری",model:"ظرفیت تولید",token:{symbol:"DAM",name:"توکن دامداری نمونه",model:"محصول‌محور",supply:3000,issued:3000,circulating:2450,holders:182},asset:{type:"دام مولد",description:"۵۰۰ راس دام مولد و ظرفیت تولید شیر و گوشت"},status:"active",validation:"pending",progress:72,value:"۱۲.۵ میلیارد",owner:"شرکت دام‌آوران",detail:"project-detail.html?id=1"},
{id:2,code:"IRT-۱۴۰۳-۰۰۲",name:"کشاورزی پایدار",domain:"کشاورزی",model:"درآمدی",token:{symbol:"AGR",name:"توکن کشاورزی پایدار",model:"درآمدی",supply:2500,issued:2500,circulating:1850,holders:126},asset:{type:"کشت و صنعت",description:"پروژه کشاورزی با تمرکز بر تولید و صادرات"},status:"active",validation:"verified",progress:45,value:"۸.۲ میلیارد",owner:"تعاونی سبز",detail:"project-detail.html?id=2"},
{id:3,code:"IRT-۱۴۰۳-۰۰۳",name:"برج تجاری آرین",domain:"املاک",model:"دارایی‌محور",token:{symbol:"ARN",name:"توکن برج تجاری آرین",model:"دارایی‌محور",supply:5000,issued:1500,circulating:900,holders:74},asset:{type:"برج تجاری",description:"ساختمان ۲۰ طبقه با کاربری اداری و تجاری"},status:"pending",validation:"pending",progress:30,value:"۴۵ میلیارد",owner:"گروه آرین",detail:"project-detail.html?id=3"},
{id:4,code:"IRT-۱۴۰۳-۰۰۴",name:"نیروگاه خورشیدی",domain:"انرژی",model:"ترکیبی",token:{symbol:"SOL",name:"توکن نیروگاه خورشیدی",model:"ترکیبی",supply:5000,issued:5000,circulating:4100,holders:248},asset:{type:"نیروگاه خورشیدی",description:"ظرفیت ۱۰ مگاوات و تولید سالانه ۱۸ گیگاوات‌ساعت"},status:"active",validation:"verified",progress:88,value:"۳۲ میلیارد",owner:"انرژی پاک",detail:"project-detail.html?id=4"},
{id:5,code:"IRT-۱۴۰۳-۰۰۵",name:"کارخانه فولاد",domain:"صنعت",model:"دارایی‌محور",token:{symbol:"STL",name:"توکن کارخانه فولاد",model:"دارایی‌محور",supply:10000,issued:2000,circulating:600,holders:38},asset:{type:"کارخانه فولاد",description:"ظرفیت تولید ۱۰۰ هزار تن در سال"},status:"paused",validation:"needs-review",progress:15,value:"۸۵ میلیارد",owner:"فولاد پارس",detail:"project-detail.html?id=5"},
{id:6,code:"IRT-۱۴۰۳-۰۰۶",name:"هتل گردشگری کیش",domain:"گردشگری",model:"درآمدی",token:{symbol:"HTL",name:"توکن هتل گردشگری کیش",model:"درآمدی",supply:8000,issued:8000,circulating:7200,holders:580},asset:{type:"هتل ۵ ستاره",description:"هتل ۲۰۰ اتاق در جزیره کیش"},status:"done",validation:"verified",progress:100,value:"۵۵ میلیارد",owner:"گروه کیش",detail:"project-detail.html?id=6"},
{id:7,code:"IRT-۱۴۰۳-۰۰۷",name:"گلخانه هوشمند دشت",domain:"کشاورزی",model:"محصول‌محور",token:{symbol:"GRN",name:"توکن گلخانه هوشمند دشت",model:"محصول‌محور",supply:4200,issued:2100,circulating:1450,holders:96},asset:{type:"گلخانه صنعتی",description:"مجموعه گلخانه‌ای هوشمند با تولید محصولات صادراتی"},status:"active",validation:"verified",progress:64,value:"۱۶ میلیارد",owner:"دشت سبز",detail:"project-detail.html?id=7"},
{id:8,code:"IRT-۱۴۰۳-۰۰۸",name:"ناوگان حمل‌ونقل پاک",domain:"حمل‌ونقل",model:"خدمت‌محور",token:{symbol:"EVT",name:"توکن ناوگان حمل‌ونقل پاک",model:"خدمت‌محور",supply:7000,issued:2800,circulating:1900,holders:141},asset:{type:"ناوگان برقی",description:"شبکه خودروهای برقی برای حمل‌ونقل شهری و بین‌شهری"},status:"pending",validation:"pending",progress:36,value:"۲۸ میلیارد",owner:"راه پاک",detail:"project-detail.html?id=8"},
{id:9,code:"IRT-۱۴۰۳-۰۰۹",name:"مجتمع لجستیک پارس",domain:"لجستیک",model:"درآمدی",token:{symbol:"LOG",name:"توکن مجتمع لجستیک پارس",model:"درآمدی",supply:9000,issued:3600,circulating:2200,holders:119},asset:{type:"مرکز لجستیک",description:"مرکز انبارش و توزیع منطقه‌ای با خدمات زنجیره تأمین"},status:"active",validation:"pending",progress:57,value:"۴۱ میلیارد",owner:"پارس لجستیک",detail:"project-detail.html?id=9"},
{id:10,code:"IRT-۱۴۰۳-۰۱۰",name:"نیروگاه بادی ساحل",domain:"انرژی",model:"درآمدی",token:{symbol:"WND",name:"توکن نیروگاه بادی ساحل",model:"درآمدی",supply:6000,issued:1800,circulating:1200,holders:82},asset:{type:"نیروگاه بادی",description:"پروژه تولید برق تجدیدپذیر با ظرفیت برنامه‌ریزی‌شده ۱۵ مگاوات"},status:"pending",validation:"pending",progress:24,value:"۶۴ میلیارد",owner:"بادآوران",detail:"project-detail.html?id=10"},
{id:11,code:"IRT-۱۴۰۳-۰۱۱",name:"مرکز درمانی نوین",domain:"سلامت",model:"حق‌محور",token:{symbol:"MED",name:"توکن مرکز درمانی نوین",model:"حق‌محور",supply:4500,issued:4500,circulating:3300,holders:214},asset:{type:"مرکز درمانی",description:"مرکز خدمات تشخیصی و درمانی با تجهیزات تخصصی"},status:"active",validation:"verified",progress:79,value:"۳۸ میلیارد",owner:"سلامت نوین",detail:"project-detail.html?id=11"},
{id:12,code:"IRT-۱۴۰۳-۰۱۲",name:"مجتمع اقامتی شمال",domain:"گردشگری",model:"مشارکتی",token:{symbol:"NRS",name:"توکن مجتمع اقامتی شمال",model:"مشارکتی",supply:6500,issued:2600,circulating:1700,holders:103},asset:{type:"مجتمع اقامتی",description:"مجموعه اقامتی و خدمات گردشگری در شمال کشور"},status:"active",validation:"pending",progress:61,value:"۲۲ میلیارد",owner:"نگین شمال",detail:"project-detail.html?id=12"},
{id:13,code:"IRT-۱۴۰۳-۰۱۳",name:"کارگاه تولید تجهیزات",domain:"فناوری",model:"مشارکتی",token:{symbol:"TEC",name:"توکن کارگاه تولید تجهیزات",model:"مشارکتی",supply:3500,issued:1000,circulating:720,holders:54},asset:{type:"خط تولید",description:"خط تولید تجهیزات هوشمند با تمرکز بر بازار صنعتی"},status:"pending",validation:"needs-review",progress:28,value:"۱۴ میلیارد",owner:"فناوران پارس",detail:"project-detail.html?id=13"},
{id:14,code:"IRT-۱۴۰۳-۰۱۴",name:"باغستان پسته کویر",domain:"کشاورزی",model:"دارایی‌محور",token:{symbol:"PST",name:"توکن باغستان پسته کویر",model:"دارایی‌محور",supply:5200,issued:3900,circulating:3000,holders:265},asset:{type:"باغ پسته",description:"باغستان تولیدی با ظرفیت برداشت و فرآوری پسته"},status:"active",validation:"verified",progress:83,value:"۱۹ میلیارد",owner:"کویر سبز",detail:"project-detail.html?id=14"},
{id:15,code:"IRT-۱۴۰۳-۰۱۵",name:"مرکز داده ابری",domain:"فناوری",model:"خدمت‌محور",token:{symbol:"CLD",name:"توکن مرکز داده ابری",model:"خدمت‌محور",supply:10000,issued:4000,circulating:2400,holders:137},asset:{type:"مرکز داده",description:"زیرساخت پردازش و ذخیره‌سازی ابری برای خدمات سازمانی"},status:"pending",validation:"pending",progress:41,value:"۷۲ میلیارد",owner:"ابر ایرانیان",detail:"project-detail.html?id=15"},
{id:16,code:"IRT-۱۴۰۳-۰۱۶",name:"مجموعه ورزشی شهری",domain:"ورزش",model:"عضویت",token:{symbol:"SPT",name:"توکن مجموعه ورزشی شهری",model:"عضویت",supply:8000,issued:8000,circulating:6200,holders:740},asset:{type:"مجموعه ورزشی",description:"مجموعه چندمنظوره با خدمات ورزشی، آموزشی و تفریحی"},status:"active",validation:"verified",progress:91,value:"۲۶ میلیارد",owner:"ورزش‌گستر",detail:"project-detail.html?id=16"}
],models:["دارایی‌محور","درآمدی","مشارکتی","حق‌محور","محصول‌محور","خدمت‌محور","عضویت","ترکیبی"],lifecycle:["پیش‌نویس","ثبت","بررسی","اعتبارسنجی","تأیید","انتشار","عرضه","فعال","تعلیق","خاتمه"]};